apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../homepage/home-prod
  - ../jellyfin/home-prod
  - ../omada-controller/home-prod
  - ../pihole/home-prod
  - ../authentik/home-prod
  - ../signalk/home-prod

images:
  - name: docker.io/tihal/omada-controller
    newTag: "6.0.0.25"
  - name: docker.io/jellyfin/jellyfin
    newTag: "10.11.5"
  - name: docker.io/pihole/pihole
    newTag: "2025.11.1"
  - name: ghcr.io/gethomepage/homepage
    newTag: latest
  - name: docker.io/signalk/signalk-server
    newTag: latest

transformers:
  - transformers/pvc-labeler-transformer.yaml # Add label to all pvcs to let pvc-update-transformer.yaml select them
  - transformers/pvc-update-transformer.yaml # Remove volumename and/or storage class from PVCs
