apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-helm-values
  namespace: kong
data:
  values.yaml: |
    crds:
      enabled: true
    gateway:
      proxy:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/address-pool: proxy-ip-pool  # Use the MetalLB address pool named "proxy-ip-pool"
