apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: proxy-certificate
  namespace: gateway
spec:
  subject:
    organizations:
      - org_placeholder
  dnsNames:
    - home.example.com
    - "*.home.example.com"
    - auth.example.com
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
