apiVersion: v1
kind: Service
metadata:
  name: omada-controller
  namespace: omada
  labels:
    app: omada-controller
  annotations:
    konghq.com/protocol: "https"
    konghq.com/verify: "false" # disables TLS verification (for self-signed certs)

spec:
  type: LoadBalancer
  # loadBalancerIP: 198.51.100.2 # Request this IP from LB
  # externalTrafficPolicy: Local # Preserve source IPs
  ports:
    - name: admin-http
      port: 80
      targetPort: 8088
    - name: admin-https
      port: 443
      targetPort: 8043
    - name: port-8088
      port: 8088
      targetPort: 8088
    - name: port-8043
      port: 8043
      targetPort: 8043
    - name: port-8843
      port: 8843
      targetPort: 8843
    - name: port-19810
      port: 19810
      targetPort: 19810
      protocol: UDP
    - name: port-27001
      port: 27001
      targetPort: 27001
      protocol: UDP
    - name: port-29810
      port: 29810
      targetPort: 29810
      protocol: UDP
    - name: port-29811
      port: 29811
      targetPort: 29811
    - name: port-29812
      port: 29812
      targetPort: 29812
    - name: port-29813
      port: 29813
      targetPort: 29813
    - name: port-29814
      port: 29814
      targetPort: 29814
    - name: port-29815
      port: 29815
      targetPort: 29815
    - name: port-29816
      port: 29816
      targetPort: 29816
    - name: port-29817
      port: 29817
      targetPort: 29817
  selector:
    app: omada-controller
