apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-smtp-credentials # name of the ExternalSecret
  namespace: authentik
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store

  target:
    name: authentik-smtp-credentials  # K8s Secret name to create
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: username
    remoteRef:
      key: authentik-smtp-username
  - secretKey: password
    remoteRef:
      key: authentik-smtp-password
