apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key # name of the ExternalSecret
  namespace: authentik
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-store

  target:
    name: authentik-secret-key  # K8s Secret name to create
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: secret_key
    remoteRef:
      key: authentik-secret-key
