# Patch to replace route hostnames
- op: replace
  path: /spec/hostnames
  value: 
    - auth.example.com         # Route to Authentik itself
    - omada.home.example.com   # Traffic routed to Authentik Embedded Outpost (Proxy Mode).
    - pihole.home.example.com  # Traffic routed to Authentik Embedded Outpost (Proxy Mode).
